# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jtZLZrX-5Oz10VgTk8OugK4CbZIXyq1l
"""

pip install nltk

pip install newspaper3k

import nltk
from newspaper import Article

url = 'https://www.cnbc.com/2020/03/19/ecb-launches-new-820-billion-coronavirus-package.html'
article= Article(url)

article.download()
article.parse()
nltk.download('punkt')
article.nlp()

# get the authors
article.authors

# get the authors
article.publish_date()

article.top_image()

print(article.text)

# get summary of the artile 
print(article.summary)



